// Generated by CoffeeScript 1.10.0
(function() {
  var express, router,db;

  express = require('express');
  router = express.Router();
  db = require('../libs/db');

  router.get('/faq', function(req, res, next) {
  	db.users.insert({test:'1'},function(err,user){
  		if(err){
  			return next(err);
  		}
  		res.json(user);
  	});
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=api.js.map
